# Generated by Django 5.1.2 on 2024-10-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peoplecounter',
            old_name='current_count',
            new_name='count',
        ),
    ]
